export const SECOND_JOB_PLACEMENT_STEP = [
  {
    key: 'important',
    text: 'As a woman when choosing an employer, what is important to you?',
    subText: 'Choose all that applies',
    answers: [
      { text: 'Maternity Leave', value: 'Maternity Leave' },
      { text: 'Working Remotely', value: 'Working Remotely' },
      { text: 'Flexible Hours', value: 'Flexible Hours' },
      { text: 'Mentorship Programs', value: 'Mentorship Programs' },
      { text: 'Compensation', value: 'Compensation' },
      { text: 'Career Development', value: 'Career Development' },
      { text: 'Leadership Opportunities', value: 'Leadership Opportunities' },
      { text: 'No Unconscious Bias', value: 'No Unconscious Bias' },
      { text: 'Onsite Childcare', value: 'Onsite Childcare' },
    ],
  },
  {
    key: 'motivation',
    text: 'What motivates you to do the best job you possibly can?',
    subText: 'Choose all that applies',
    answers: [
      { text: 'Work life balance', value: 'Work life balance' },
      { text: 'Reward performance', value: 'Reward performance' },
      { text: 'Corporate perks', value: 'Corporate perks' },
      { text: 'Workplace friendship', value: 'Workplace friendship' },
      { text: 'Pride in work', value: 'Pride in work' },
      { text: 'PTO flexibility', value: 'PTO flexibility' },
      { text: 'Open communication', value: 'Open communication' },
      { text: 'Team work', value: 'Team work' },
      { text: 'Job security', value: 'Job security' },
    ],
  },
  {
    key: 'deal_break',
    text: 'What is a deal breaker for you?',
    subText: 'Choose all that applies',
    answers: [
      { text: 'Process heavy', value: 'Process heavy' },
      { text: 'Micromanagement', value: 'Micromanagement' },
      { text: 'Lack work flexibility', value: 'Lack work flexibility' },
      { text: 'Too many changes', value: 'Too many changes' },
      { text: 'High stress', value: 'High stress' },
      { text: 'Lack family life balance', value: 'Lack family life balance' },
      { text: 'Incompetent Leadership', value: 'Incompetent Leadership' },
      { text: 'High stress', value: 'High stress' },
      { text: 'Insurance Coverage', value: 'Insurance Coverage' },
      { text: 'Office politics', value: 'Office politics' },
    ],
  },
];
